name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

jobs:
  build-validate-pref-tests:
    name: run performance tests
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: Install and build
        run: $HOME/.yarn/bin/yarn install --immutable
    
      - name: Set execute permission for script
        run: chmod +x ./reassure-tests.sh

      - name: Run performance tests
        run: ./reassure-tests.sh

      - name: Run Danger.js
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
